export const selarylist = [
    {
      id: 1,
      name: 'Kirill Konev',
      today: '20',
      daylyaverage: '30',
      midwayselary: '150',
      finalselary: '450',
      worker: 'Kirill Konev',
    },
    {
        id: 1,
        name: 'Lesha Konoyko',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'Lesha Konoyko',
      },
      {
        id: 1,
        name: 'Vasa Pupkin',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'Vasa Pupkin',
      },
      {
        id: 1,
        name: 'Victor Zhelud',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'Victor Zhelud',
      },
      {
        id: 1,
        name: 'Bob Bobson',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'Bob Bobson',
      },
      {
        id: 1,
        name: 'Bob Jonson',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'Bob Jonson',
      },
      {
        id: 1,
        name: 'Gorge Gouson',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'Gorge Gouson',
      },
      {
        id: 1,
        name: 'Ser Hendrik the 3rd',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'Ser Hendrik the 3rd',
      },
      {
        id: 1,
        name: 'Maxim Kostukovich',
        today: '0',
        daylyaverage: '0',
        midwayselary: '0',
        finalselary: '0',
        worker: 'Maxim Kostukovich',
      },{
        id: 1,
        name: 'Round Bob',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'Round Bob',
      },{
        id: 1,
        name: 'David Guetta',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'David Guetta',
      },{
        id: 1,
        name: 'i dont',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'i dont',
      },{
        id: 1,
        name: 'Know What',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'Know What',
      },{
        id: 1,
        name: '1',
        today: 'To Write',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'To Write',
      },{
        id: 1,
        name: 'The End',
        today: '20',
        daylyaverage: '30',
        midwayselary: '150',
        finalselary: '450',
        worker: 'The End',
      },
  ];
  